name: BuildPackages

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
#   push:
#     branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab

  workflow_dispatch:
    inputs:
      publish:
        type: boolean
        description: 'Publish to nugget server'     
        required: false
        default: false

env:
  PROJECTDIR: 'Helpers' #folder where project file is
  NUGET_SERVER: 'https://api.nuget.org/v3/index.json'
  NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
  NUGETAPIKEY : ${{secrets.NUGETAPIKEY}}

jobs:
  publish:
    runs-on: windows-latest #self-hosted #windows-latest
    strategy:
      matrix:
        dotnet-version: [ '7.0.x' ]

    steps:
    - uses: actions/checkout@v4

    # https://github.com/actions/setup-dotnet
    # TODO To speed up dependencies see also: https://docs.github.com/en/actions/guides/caching-dependencies-to-speed-up-workflows
    - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v4 
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
        source-url: ${{ env.NUGET_SERVER }}  # test adresy:
          
    - name: Install dependencies
    #install required packeges
      run: |
        dotnet restore $env:PROJECTDIR 
    
    - name: Build
      run: |
        dotnet build --configuration Release --no-restore $env:PROJECTDIR

    - name: Parametres
      run: |
          echo "event_name: ${{github.event_name}}"
          echo "inputs.publish: ${{github.event.inputs.publish}}"
      
    - name: Package
      run: |
        dotnet pack --configuration Release -p:PackageVersion=1.0.$env:GITHUB_RUN_NUMBER $env:PROJECTDIR

    - name: Publish the package
      if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.publish=='true' }}
      run: |
        dotnet nuget push $env:PROJECTDIR\bin\Release\*.nupkg -k $env:NUGETAPIKEY
