name: PublishToPowershellGallery

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
#   push:
#     branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab

  workflow_dispatch:
    inputs:
      publish:
        type: boolean
        description: 'Publish to powershell gallery'     
        required: false
        default: false

env:
  PROJECTDIR: 'Helpers' #folder where project file is
  NUGET_SERVER: 'https://api.nuget.org/v3/index.json'
  NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
  POWERSHELL_API_KEY : ${{secrets.POWERSHELL_API_KEY}}
  
jobs:
  publish:
    runs-on: windows-latest #self-hosted #windows-latest
    steps:
    - uses: actions/checkout@v4

    # - name: Install prerequisites
    #   shell: pwsh
    #   run: |
    #    Install-Module Utilities -AllowClobber

    - name: Initialize environment
      uses: PSModule/Initialize-PSModule@main

    - name: PrepareFiles
      run: |
            mkdir outputModule
            New-Item -Path "outputModule\helpers" -ItemType Directory -Force
    - name: CopyingFiles
      run: |
            Copy-Item -Path (Join-Path $env:GITHUB_WORKSPACE "helpers") -Destination (Join-Path $env:GITHUB_WORKSPACE "outputModule") -Recurse -Force
            Get-ChildItem -Path $env:GITHUB_WORKSPACE -Recurse -Include "*.psd1", "*.psm1" | Copy-Item -Destination (Join-Path $env:GITHUB_WORKSPACE "outputModule") -Force

    - name: Publish-PSModule
      uses: PSModule/Publish-PSModule@main
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        APIKey: ${{env.POWERSHELL_API_KEY}}
        ModulePath: "outputModule"