name: ScriptExample
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  ARTIFACT_NAME: "Liberec"
  VAR_1: ${{vars.VAR_1}}

jobs:

    # This workflow contains a single job called "build"
    checkOut:
        # The type of runner that the job will run on
        runs-on: [self-hosted] #ubuntu-latest #windows-latest
        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
          - name: checkout
            uses: actions/checkout@v2
    
    vypisSoubory:
        runs-on: [self-hosted]
        needs: checkOut 
        steps:

        - name: Skript
          shell: pwsh
          run: |
                .\SomeScript.ps1 -Directory (Get-Location).Path 
    
    useEnv:
        runs-on: [self-hosted]
        needs: checkOut 
        steps:
          - name: Vypis ARTIFACT_NAME
            shell: pwsh
            run: |
                  echo ARTIFACT_NAME is now: ${{env.ARTIFACT_NAME}} 
                  echo POKUS: ${{env.POKUS}} 
                  echo VAR_1: ${{env.VAR_1}} 

    pokusOs:
       runs-on: ${{ matrix.os }}              
       strategy:    # multiple options to combine
        matrix:
          os: [ubuntu-latest, self-hosted]
    
       steps:
            - name: Vypis OS
              shell: pwsh
              run: |
                    echo Current os is: ${{ matrix.os }}
           